

multipart.maxFileSize: 5MB
multipart.maxRequestSize: 5MB

---
spring:
  profiles: cloud
  application:
    name: ${vcap.application.name:s3-sample-app}
amazon:
  aws:
    access-key-id: ${vcap.services.s3-sample-service.credentials.aws-key-id}
    access-key-secret: ${vcap.services.s3-sample-service.credentials.aws-key-secret}
  s3:
    default-bucket: ${vcap.services.s3-sample-service.credentials.default-bucket}
    

---
spring:
  profiles: local
  application:
    name: s3-sample-app
amazon:
  aws:
    access-key-id: AKIAJUXNBI3LQLSCQZCA
    access-key-secret: 421ojQu2XNf1vvbXZfQI74aoi3mciyBHapb4xNUL
  s3:
    default-bucket: poc-pipeline
